image:
  name: 971715240952.dkr.ecr.eu-central-1.amazonaws.com/rb-pipeline:latest
  aws:
    access-key: $PIPELINE_ECR_ACCESS_KEY
    secret-key: $PIPELINE_ECR_SECRET_KEY
clone:
  lfs: true
definitions:
  caches:
    pnpm: $BITBUCKET_CLONE_DIR/.pnpm-store
  steps:
    - step: &testStep
        name: Test
        caches:
          - pnpm
        script:
          - npm install -g pnpm@latest-6
          - pnpm config set '//npm.pkg.github.com/:_authToken' ${GITHUB_TOKEN}
          - pnpm install --frozen-lockfile
          - pnpm run type-check
          - pnpm run lint
    - step: &deployStep
        name: Deploy dev
        deployment: dev
        caches:
          - pnpm
        script:
          - npm install -g pnpm@latest-6
          - pnpm config set '//npm.pkg.github.com/:_authToken' ${GITHUB_TOKEN}
          - pnpm install --frozen-lockfile
          - pnpm run i18next:download
          - pnpm run i18next:download:rowan
          - VERSION="${BITBUCKET_TAG:-${BITBUCKET_COMMIT}}" CHEATS="${CHEATS}" GA_DATA_FLOW_ID="${GA_DATA_FLOW_ID}" pnpm run build
          - /scripts/deploy_cloudfront.sh --game
    - step: &NightlyCheck
        name: Nightly Check
        clone:
          enabled: false
        script:
          - /scripts/nightly_check.sh
    - step: &localazy
        name: Run localazy
        caches:
          - pnpm
        script:
          - npm install -g pnpm@latest-6
          - pnpm config set '//npm.pkg.github.com/:_authToken' ${GITHUB_TOKEN}
          - pnpm install --frozen-lockfile
          - pnpm run i18next:parse
          - pnpm run i18next:upload
pipelines:
  custom:
    nightly:
      - step: *NightlyCheck
      - step: *testStep
      - step: *deployStep
  branches:
    main:
      - step: *localazy

